<?php

namespace Teimur\YiiPhoneConfirm\forms;

use borales\extensions\phoneInput\PhoneInputValidator;
use Teimur\YiiPhoneConfirm\Config;
use Teimur\YiiPhoneConfirm\ConfirmTokenService;
use Yii;
use yii\base\Model;

/**
 * Login form
 */
class ConfirmEmailForm extends Model
{
    public $email;
    public $token;
    public $type;
    private $_token;
    
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['email', 'trim'],
            [['email', 'token'], 'required'],
            [['email'], 'email'],
            [['email'], 'exist', 'targetClass' => Config::getUserClass(), 'targetAttribute' => 'email'],
        ];
    }
    
    public function afterValidate()
    {
        parent::afterValidate(); // TODO: Change the autogenerated stub
        
        /** @var ConfirmTokenService $service */
        $service = Yii::createObject(ConfirmTokenService::class);

        try {
            $this->_token = $service->validateEmailToken($this->email, $this->token);
        } catch (\Exception $e) {
            $this->addError('token', $e->getMessage());
            
            return false;
        }
        
    }
    
    public function getToken()
    {
        return $this->_token;
    }
    
    public function tokenActionIs($action)
    {
        return $this->_token->action == $action;
    }
}
