<?php

namespace Teimur\YiiPhoneConfirm;

use yii\base\Component;

class Config extends Component
{
    public $user;
    
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
